# Generated by Django 5.2.12 on 2026-03-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
