# Generated by Django 5.2.12 on 2026-03-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_registereduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='account_role',
            field=models.CharField(blank=True, default='employee', max_length=16),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='dob_display',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
