# Generated by Django 5.2.12 on 2026-03-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_registereduser_account_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
