# Generated by Cursor on 2026-03-18

from django.db import migrations, models
from django.contrib.auth.hashers import make_password


def seed_admin(apps, schema_editor):
    AdminAccount = apps.get_model("attendance", "AdminAccount")
    email = "admin@gmail.com"
    if AdminAccount.objects.filter(email__iexact=email).exists():
        return
    AdminAccount.objects.create(email=email, password_hash=make_password("admin123@"))


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0005_registereduser_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password_hash", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["email"],
            },
        ),
        migrations.RunPython(seed_admin, migrations.RunPython.noop),
    ]

