# Generated by Django 5.2.12 on 2026-03-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_adminaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='geofence',
            field=models.CharField(blank=True, default='Main Entrance', max_length=255),
        ),
    ]
