# Generated by Django 5.2.12 on 2026-04-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendancerecord_geofence'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
