# Generated by Django 5.2.12 on 2026-04-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendancerecord_latitude_attendancerecord_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofenceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Site', max_length=255)),
                ('latitude', models.FloatField(default=26.118)),
                ('longitude', models.FloatField(default=91.8136)),
                ('radius', models.FloatField(default=500.0)),
                ('verification_method', models.CharField(default='GPS Only', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Geofence Setting',
                'verbose_name_plural': 'Geofence Settings',
            },
        ),
    ]
