# Generated by Django 5.2.12 on 2026-04-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='admin_email',
            field=models.EmailField(default='admin@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='enable_reminder_sound',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='reminder_interval',
            field=models.CharField(default='Daily Reminders', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='reminder_time',
            field=models.TimeField(default='08:30'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='retention_days',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='system_name',
            field=models.CharField(default='Attendance Portal v2.0', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=255),
        ),
    ]
