# Generated by Django 5.2.12 on 2026-04-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_systemsetting_admin_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsetting',
            name='system_name',
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='default_language',
            field=models.CharField(default='English', max_length=255),
        ),
    ]
