# Generated by Django 5.2.12 on 2026-04-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_remove_systemsetting_system_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsetting',
            name='default_language',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='timezone',
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='max_login_attempts',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='session_timeout',
            field=models.IntegerField(default=30),
        ),
    ]
