# Generated by Django 5.2.12 on 2026-05-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_remindersound'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
